function J = JJ_2322(in1,L,H,xi,eta)
%JJ_2322
%    J = JJ_2322(IN1,L,H,XI,ETA)

%    This function was generated by the Symbolic Math Toolbox version 7.2.
%    06-Mar-2018 09:05:29

ee1 = in1(1,:);
ee2 = in1(2,:);
ee3 = in1(3,:);
ee4 = in1(4,:);
ee5 = in1(5,:);
ee6 = in1(6,:);
ee7 = in1(7,:);
ee8 = in1(8,:);
ee9 = in1(9,:);
ee10 = in1(10,:);
ee11 = in1(11,:);
ee12 = in1(12,:);
t2 = H.^2;
t3 = xi.^2;
J = (-H.*ee1.*ee8+H.*ee2.*ee7-H.*ee7.*ee10+H.*ee8.*ee9-ee3.*ee8.*eta.*t2.*(1.0./2.0)+ee4.*ee7.*eta.*t2.*(1.0./2.0)-ee7.*ee12.*eta.*t2.*(1.0./2.0)+ee8.*ee11.*eta.*t2.*(1.0./2.0)-H.*ee1.*ee4.*t3.*(3.0./2.0)+H.*ee2.*ee3.*t3.*(3.0./2.0)+H.*ee1.*ee8.*t3-H.*ee2.*ee7.*t3-H.*ee3.*ee6.*t3.*2.0+H.*ee4.*ee5.*t3.*2.0+H.*ee1.*ee12.*t3.*(1.0./2.0)-H.*ee2.*ee11.*t3.*(1.0./2.0)+H.*ee3.*ee10.*t3.*(1.0./2.0)-H.*ee4.*ee9.*t3.*(1.0./2.0)-H.*ee5.*ee12.*t3.*2.0+H.*ee6.*ee11.*t3.*2.0+H.*ee7.*ee10.*t3-H.*ee8.*ee9.*t3+H.*ee9.*ee12.*t3.*(3.0./2.0)-H.*ee10.*ee11.*t3.*(3.0./2.0)+H.*ee1.*ee4.*xi.*(1.0./2.0)-H.*ee2.*ee3.*xi.*(1.0./2.0)+H.*ee1.*ee8.*xi.*2.0-H.*ee2.*ee7.*xi.*2.0-H.*ee1.*ee12.*xi.*(1.0./2.0)+H.*ee2.*ee11.*xi.*(1.0./2.0)+H.*ee3.*ee10.*xi.*(1.0./2.0)-H.*ee4.*ee9.*xi.*(1.0./2.0)-H.*ee5.*ee8.*xi.*4.0+H.*ee6.*ee7.*xi.*4.0-H.*ee7.*ee10.*xi.*2.0+H.*ee8.*ee9.*xi.*2.0+H.*ee9.*ee12.*xi.*(1.0./2.0)-H.*ee10.*ee11.*xi.*(1.0./2.0)+H.*ee1.*ee4.*t3.*xi-H.*ee2.*ee3.*t3.*xi-H.*ee1.*ee8.*t3.*xi.*2.0+H.*ee2.*ee7.*t3.*xi.*2.0+H.*ee3.*ee6.*t3.*xi.*2.0-H.*ee4.*ee5.*t3.*xi.*2.0+H.*ee1.*ee12.*t3.*xi-H.*ee2.*ee11.*t3.*xi-H.*ee3.*ee10.*t3.*xi+H.*ee4.*ee9.*t3.*xi+H.*ee5.*ee8.*t3.*xi.*4.0-H.*ee6.*ee7.*t3.*xi.*4.0-H.*ee5.*ee12.*t3.*xi.*2.0+H.*ee6.*ee11.*t3.*xi.*2.0+H.*ee7.*ee10.*t3.*xi.*2.0-H.*ee8.*ee9.*t3.*xi.*2.0+H.*ee9.*ee12.*t3.*xi-H.*ee10.*ee11.*t3.*xi-ee3.*ee8.*eta.*t2.*t3.*(1.0./2.0)+ee4.*ee7.*eta.*t2.*t3.*(1.0./2.0)+ee3.*ee12.*eta.*t2.*t3.*(1.0./2.0)-ee4.*ee11.*eta.*t2.*t3.*(1.0./2.0)-ee7.*ee12.*eta.*t2.*t3.*(1.0./2.0)+ee8.*ee11.*eta.*t2.*t3.*(1.0./2.0)+ee3.*ee8.*eta.*t2.*xi-ee4.*ee7.*eta.*t2.*xi-ee7.*ee12.*eta.*t2.*xi+ee8.*ee11.*eta.*t2.*xi)./(H.*L);
